const TREE_FILE_ICON_SRC_BY_EXTENSION: Record<string, string> = {
  astro: "/icons/astro.svg",
  avif: "/icons/image.svg",
  bmp: "/icons/image.svg",
  c: "/icons/c.svg",
  cpp: "/icons/cpp.svg",
  css: "/icons/css.svg",
  csv: "/icons/csv.svg",
  gif: "/icons/image.svg",
  go: "/icons/go.svg",
  html: "/icons/html.svg",
  ico: "/icons/image.svg",
  java: "/icons/java.svg",
  jpeg: "/icons/image.svg",
  jpg: "/icons/image.svg",
  js: "/icons/javascript.svg",
  json: "/icons/json.svg",
  jsx: "/icons/react.svg",
  m4a: "/icons/audio.svg",
  markdown: "/icons/markdown.svg",
  md: "/icons/markdown.svg",
  mkv: "/icons/video.svg",
  mov: "/icons/video.svg",
  mp3: "/icons/audio.svg",
  mp4: "/icons/video.svg",
  pdf: "/icons/pdf.svg",
  php: "/icons/php.svg",
  png: "/icons/image.svg",
  py: "/icons/python.svg",
  rb: "/icons/ruby.svg",
  rs: "/icons/rust.svg",
  scss: "/icons/scss.svg",
  sql: "/icons/database.svg",
  svg: "/icons/svg.svg",
  tar: "/icons/zip.svg",
  ts: "/icons/typescript.svg",
  tsx: "/icons/react-typescript.svg",
  txt: "/icons/text.svg",
  wav: "/icons/audio.svg",
  webm: "/icons/video.svg",
  webp: "/icons/image.svg",
  xls: "/icons/csv.svg",
  xlsx: "/icons/csv.svg",
  xml: "/icons/xml.svg",
  yaml: "/icons/yaml.svg",
  yml: "/icons/yaml.svg",
  zip: "/icons/zip.svg",
};

export function getSidebarTreeFileIconSrc(name: string) {
  const ext = name.includes(".")
    ? (name.split(".").pop()?.toLowerCase() ?? "")
    : "";
  return TREE_FILE_ICON_SRC_BY_EXTENSION[ext] ?? "/icons/_file.svg";
}
