import type {
  BrowseSurfaceProps,
  BuildExplorerBrowsePanePropsOptions,
} from "@/components/files/explorer/explorer-browse-pane-props-shared";

export function buildExplorerBrowseSurfaceProps({
  allFolders,
  contextMenuSurfaceClass,
  dropTargetId,
  explorerEntries,
  folderFileCount,
  folderPreviewKinds,
  folderSubfolderCount,
  getFileDragProps,
  getFileIcon,
  getFileItemActionProps,
  getFileKind,
  getFolderDragProps,
  getFolderItemActionProps,
  hoveredPreviewFileId,
  interactions,
  isMobile,
  itemActionTargetSelector,
  listMeasureElement,
  listTotalSize,
  listVirtualItems,
  onChangeFolderBanner,
  onCreateFolder,
  onOpenFile,
  onOpenFolder,
  onPreviewIntentEnd,
  onPreviewIntentStart,
  onResetFolderBanner,
  selectedCardPropertyDefinitions,
  selection,
  setItemRowRefMap,
  sortedFiles,
  sortedFolders,
  viewMode,
  visibleItemIds,
}: BuildExplorerBrowsePanePropsOptions): BrowseSurfaceProps {
  return {
    allFolders,
    contextMenuSurfaceClass,
    dropTargetId,
    explorerEntries,
    folderFileCount,
    folderPreviewKinds,
    folderSubfolderCount,
    getFileDragProps,
    getFileIcon,
    getFileItemActionProps,
    getFileKind,
    getFolderDragProps,
    getFolderItemActionProps,
    hoveredPreviewFileId,
    interactions,
    isMobile,
    itemActionTargetSelector,
    listMeasureElement,
    listTotalSize,
    listVirtualItems,
    onChangeFolderBanner,
    onCreateFolderHere: onCreateFolder,
    onOpenFile,
    onOpenFolder,
    onPreviewIntentEnd,
    onPreviewIntentStart,
    onResetFolderBanner,
    selectedCardPropertyDefinitions,
    selection,
    setItemRowRef: (itemId, node) => {
      if (!node) {
        setItemRowRefMap.current.delete(itemId);
        return;
      }
      setItemRowRefMap.current.set(itemId, node);
    },
    sortedFiles,
    sortedFolders,
    viewMode,
    visibleItemIds,
  };
}
