import type {
  BuildExplorerBrowsePanePropsOptions,
  ControlsProps,
} from "@/components/files/explorer/explorer-browse-pane-props-shared";

export function buildExplorerControlsProps({
  availablePropertyDefinitions,
  canNavigateUp,
  canRedoFileOperation,
  canUndoFileOperation,
  cardFieldQuery,
  cardPropertyKeys,
  currentFolderId,
  currentLocationTitle,
  fileOperationHistoryBusy,
  filteredAvailablePropertyDefinitions,
  handlePropertyFiltersChange,
  isCurrentFolderReadOnly,
  isMobile,
  contextMenuSurfaceClass,
  onCardFieldQueryChange,
  onCardFieldToggle,
  onClearCardFields,
  onCreateFolder,
  onCreateNote,
  onImportLink,
  onNavigateUp,
  onOpenMobileCreateMenu,
  onRedo,
  onResetCardFields,
  onUndo,
  onUploadFile,
  onUploadFolder,
  propertyFilterFields,
  propertyFiltersForUi,
  selectedCardPropertyDefinitions,
  setSortState,
  setViewMode,
  sortState,
  viewMode,
}: BuildExplorerBrowsePanePropsOptions): ControlsProps {
  return {
    availablePropertyDefinitions,
    canNavigateUp,
    canRedoFileOperation,
    canUndoFileOperation,
    cardFieldQuery,
    cardPropertyKeys,
    currentFolderId,
    currentLocationTitle,
    fileOperationHistoryBusy,
    filteredAvailablePropertyDefinitions,
    isCurrentFolderReadOnly,
    isMobile,
    menuSurfaceClass: contextMenuSurfaceClass,
    onCardFieldQueryChange,
    onCardFieldToggle,
    onClearCardFields,
    onCreateFolder,
    onCreateNote,
    onImportLink,
    onNavigateUp,
    onOpenMobileCreateMenu,
    onPropertyFiltersChange: handlePropertyFiltersChange,
    onRedo,
    onResetCardFields,
    onSortChange: setSortState,
    onUndo,
    onUploadFile,
    onUploadFolder,
    onViewModeChange: setViewMode,
    propertyFilterFields,
    propertyFiltersForUi,
    selectedCardPropertyDefinitions,
    sortState,
    viewMode,
  };
}
